name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Build project
        run: pnpm build
        working-directory: review-app-vite # Specify the working directory for the build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./review-app-vite/dist # Specify the directory to publish
          publish_branch: gh-pages # The branch to deploy to
